 
version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: retailersrewards
    networks:
      springboot-mysql-net:
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysqldb:/var/lib/mysql
# Names our volume
volumes:
  mysqldb:
  
  retailer-reward-restful-webservices:
    container_name: retailer-reward
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    expose:
      # Opens port 3306 on the container
      - '8080' 
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: